services:
  my_laravel_container:
    build:
      context: .
      dockerfile: dockerfile
      args:
        UID: 1000
        GID: 1000
    image: back-laravel
    container_name: my_laravel_container
    ports:
      - "8080:80"
    networks:
      - my_net
    volumes:
      - ./LaravelServer:/var/www/html
    environment:
      - TZ=America/Mexico_City

# Utilizo una red externa creada previamente, 
# para crearla usar: docker network create my_net
networks:
  my_net:
    external: true